### ISSUE TITLE
Summary editor

### ISSUE THREAD

**Issue by skeptic17** [newsvoice/newsvoice#271] opened 2020-02-26 15:42 UTC
The characters {[}] are silently removed when submitting a summary. That is, I wrote "[sic]" in a summary and it was changed to "sic". I didn't notice it and submitted with it missing the brackets.

They are allowed in the title.

Also, as noted before, the title is not spell-checked so more spelling errors appear in titles than in summaries.

**Comment by vlidholt** [comment] 2020-03-09 12:51
Title should probably be spell checked. The brackets are used internally for highlighting changes in the summaries, so cannot change those at the moment. Generally, I think it's good practice to leave those out of summaries anyway.

**Comment by vlidholt** [comment] 2020-03-09 12:52
Duplicate of #266, closing.

**Closed as completed by vlidholt** 2020-03-09 12:52 UTC
Labels: enhancement
